config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :stores
  get 'home/index'

  root 'home#index'

  get 'services/stores', :to => 'stores#service_index'
  get 'services/articles', :to => 'articles#service_index'
  get 'services/articles/stores/:id', :to => 'articles#service_articles_by_store'
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :store
	
	validates :name, presence: true, length: { minimum: 3 }
	validates :description, presence: true, length: { minimum: 5 }
	validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
	validates :total_in_shelf, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
	validates :total_in_vault, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	
	validates :name, presence: true, length: { minimum: 3 }
	validates :address, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == USER_ID && password == PASSWORD
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :only => [:service_index, :service_articles_by_store]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.includes(:store)
  end

  # List all articles service.
  # GET /services/articles
  def service_index
    @articles = Article.includes(:store)
    render json: { articles: @articles, success: true, total_elements: @articles.count }
  end

  # List all the articles that are in a specific store service.
  # GET /services/articles/stores/:id
  def service_articles_by_store
    begin
      i = Integer(params[:id])
      @articles = Article.where(:store_id => i)
      
      if(@articles.count > 0)
        render json: { articles: @articles, success: true, total_elements: @articles.count }
      else
        render json: { error_msg: 'Record not Found', error_code: 404, success: false }
      end
    rescue ArgumentError
      render json: { error_msg: 'Bad Request', error_code: 400, success: false}
    end
  end
  
  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :only => [:service_index]
  
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # List all stores service.
  # GET /services/stores
  def service_index
    @stores = Store.all
    render json: {stores: @stores, success: true, total_elements: @stores.count}
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field form-group">
    <%= f.label :total_in_shelf %><br>
    <%= f.number_field :total_in_shelf %>
  </div>
  <div class="field form-group">
    <%= f.label :total_in_vault %><br>
    <%= f.number_field :total_in_vault %>
  </div>
  <div class="field form-group">
    <%= f.label :store_id %><br>
    <%= f.select :store_id, options_from_collection_for_select(Store.all, :id, :name, @article.store_id) %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-responsive">
  <h1>Listing Articles</h1>

  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Total in shelf</th>
        <th>Total in vault</th>
        <th>Store</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.name %></td>
          <td><%= article.description %></td>
          <td><%= article.price %></td>
          <td><%= article.total_in_shelf %></td>
          <td><%= article.total_in_vault %></td>
          <td><%= article.store.name %></td>
          <td><%= link_to 'Show', article %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Article', new_article_path %>
<br>
<br>
<%= link_to 'Back to Main Menu', root_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<p>
  <strong>Total in shelf:</strong>
  <%= @article.total_in_shelf %>
</p>

<p>
  <strong>Total in vault:</strong>
  <%= @article.total_in_vault %>
</p>

<p>
  <strong>Store:</strong>
  <%= @article.store.name %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<h1>Main Menu</h1>
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Manage Stores</th>
        <th>Manage Articles</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= link_to 'Stores', stores_path %></td>
        <td><%= link_to 'Articles', articles_path %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/_footer.html.erb
Copyright 2016

app/views/layouts/_header.html.erb
<img class="img-responsive img-circle" src="<%= image_url('supershoes.png') %>" alt="Chania" width="204" height="136">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperShoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<%=yield %>
<br />
<br />
<%= render "layouts/footer" %>

</body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>
<div class="table-responsive">
  <h1>Listing Stores</h1>

  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td><%= store.name %></td>
          <td><%= store.address %></td>
          <td><%= link_to 'Show', store %></td>
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Store', new_store_path %>
<br>
<br>
<%= link_to 'Back to Main Menu', root_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>